### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by YzLrc** [jaspereb/Retinanet-Tutorial#5]
could you please help with the following errors?
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 556, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 486, in main
    train_generator, validation_generator = create_generators(args, backbone.preprocess_image)
  File "keras_retinanet/bin/train.py", line 289, in create_generators
    **common_args
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/pascal_voc.py", line 85, in __init__
    super(PascalVocGenerator, self).__init__(**kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 89, in __init__
    self.group_images()
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 291, in group_images
    order.sort(key=lambda x: self.image_aspect_ratio(x))
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 291, in <lambda>
    order.sort(key=lambda x: self.image_aspect_ratio(x))
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/pascal_voc.py", line 121, in image_aspect_ratio
    image = Image.open(path)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ps/Retinanet/animalsVOC/JPEGImages/Bathc0_31.jpg'

**Comment by YzLrc** [comment]
and i just followed yourt tutorial to create all the folders，why whould this path problem happen？I have been struggled for a long time！

**Comment by jaspereb** [comment]
what happens when you run `ls /home/ps/Retinanet/animalsVOC/JPEGImages/Bathc0_31.jpg' ?

**Comment by YzLrc** [comment]
> what happens when you run `ls /home/ps/Retinanet/animalsVOC/JPEGImages/Bathc0_31.jpg' ?

thank you for your quick reply。I have rechecked my image file just now，I have some error on naming the image file and i have fixed it，now it works well！！

**Comment by YzLrc** [comment]
sorry，I just can‘t understand！I’ve followed every step which you wrote on github，and how can I solve it？Thanks again.





------------------ Original ------------------

**Comment by jaspereb** [comment]
you said you fixed that error? what is the current issue?

**Comment by YzLrc** [comment]
oh I have just send a new issue，which name is“the problem with testDetector.py” .Maybe you have checked the old issue.





------------------ Original ------------------
