### ISSUE TITLE
the problem with testDetector.py

### ISSUE THREAD

**Issue by YzLrc** [jaspereb/Retinanet-Tutorial#6]

**Comment by YzLrc** [comment]
hi,I've just met a new porblem when I run the testDetector.py. Hope you can help me check it out.
Traceback (most recent call last):
  File "testDetector.py", line 54, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')
  File "/home/ps/.local/lib/python3.6/site-packages/keras_retinanet/models/__init__.py", line 87, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/ps/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Functional

**Comment by jaspereb** [comment]
might be a tf version issue, are you using tensorflow 1.11?

`pip install tensorflow-gpu==1.11`

**Comment by YzLrc** [comment]
ok I‘ll try it！





------------------ Original ------------------
